language: php
sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "short_open_tag = On" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
  - mysql -e 'CREATE DATABASE concrete5_tests;'
  - cd web/concrete
  - composer install
  - cd ../../tests

script: phpunit

notifications:
  email: false

matrix:
  allow_failures:
    - php: hhvm
